package ResourceStrings;

public class DDS {
	
	public static final String AT = "AT";
	public static final String AT_FP = "./Data_DDS/AT.csv";
	public static final String ATaaUC = "ATaaUC";
	public static final String ATaaUC_FP = "./Data_DDS/ATaaUC.csv";
	public static final String BGR = "BGR";
	public static final String BGR_FP = "./Data_DDS/BGR.csv";
	public static final String BGRaaCLS = "BGRaaCLS";
	public static final String BGRaaCLS_FP = "./Data_DDS/BGRaaCLS.csv";
	public static final String CLS = "CLS";
	public static final String CLS_FP = "./Data_DDS/CLS.csv";
	public static final String CLSaaUT = "CLSaaUT";
	public static final String CLSaaUT_FP = "./Data_DDS/CLSaaUT.csv";
	public static final String DRQ = "DRQ";
	public static final String DRQ_FP = "./Data_DDS/DRQ.csv";
	public static final String DRQaaCLS = "DRQaaCLS";
	public static final String DRQaaCLS_FP = "./Data_DDS/DRQaaCLS.csv";
	public static final String DRQaaEA = "DRQaaEA";
	public static final String DRQaaEA_FP = "./Data_DDS/DRQaaEA.csv";
	public static final String EA = "EA";
	public static final String EA_FP = "./Data_DDS/EA.csv";
	public static final String EAaaCLS = "EAaaCLS";
	public static final String EAaaCLS_FP = "./Data_DDS/EAaaCLS.csv";
	public static final String FLT = "FLT";
	public static final String FLT_FP = "./Data_DDS/FLT.csv";
	public static final String FLTaaSRQ = "FLTaaSRQ";
	public static final String FLTaaSRQ_FP = "./Data_DDS/FLTaaSRQ.csv";
	public static final String GL = "GL";
	public static final String GL_FP = "./Data_DDS/GL.csv";
	public static final String GLaaPJT = "GLaaPJT";
	public static final String GLaaPJT_FP = "./Data_DDS/GLaaPJT.csv";
	public static final String GLaaSRQ = "GLaaSRQ";
	public static final String GLaaSRQ_FP = "./Data_DDS/GLaaSRQ.csv";
	public static final String HZD = "HZD";
	public static final String HZD_FP = "./Data_DDS/HZD.csv";
	public static final String HZDaaFLT = "HZDaaFLT";
	public static final String HZDaaFLT_FP = "./Data_DDS/HZDaaFLT.csv";
	public static final String PJT = "PJT";
	public static final String PJT_FP = "./Data_DDS/PJT.csv";
	public static final String PJTaaPPL = "PJTaaPPL";
	public static final String PJTaaPPL_FP = "./Data_DDS/PJTaaPPL.csv";
	public static final String PPL = "PPL";
	public static final String PPL_FP = "./Data_DDS/PPL.csv";
	public static final String PPLaaBGR = "PPLaaBGR";
	public static final String PPLaaBGR_FP = "./Data_DDS/PPLaaBGR.csv";
	public static final String SRQ = "SRQ";
	public static final String SRQ_FP = "./Data_DDS/SRQ.csv";
	public static final String SRQaaSSRQ = "SRQaaSSRQ";
	public static final String SRQaaSSRQ_FP = "./Data_DDS/SRQaaSSRQ.csv";
	public static final String SSRQ = "SSRQ";
	public static final String SSRQ_FP = "./Data_DDS/SSRQ.csv";
	public static final String SSRQaaDRQ = "SSRQaaDRQ";
	public static final String SSRQaaDRQ_FP = "./Data_DDS/SSRQaaDRQ.csv";
	public static final String UC = "UC";
	public static final String UC_FP = "./Data_DDS/UC.csv";
	public static final String UCaaGL = "UCaaGL";
	public static final String UCaaGL_FP = "./Data_DDS/UCaaGL.csv";
	public static final String UT = "UT";
	public static final String UT_FP = "./Data_DDS/UT.csv";
	public static final String UTaaUTL = "UTaaUTL";
	public static final String UTaaUTL_FP = "./Data_DDS/UTaaUTL.csv";
	public static final String UTL = "UTL";
	public static final String UTL_FP = "./Data_DDS/UTL.csv";
	// TM of two table join
	public static final String SRQaaDRQ = "SRQaaDRQ";
	public static final String SRQaaDRQ_FP = "./Data_DDS/SRQaaDRQ.csv";
	public static final String SSRQaaCLS = "SSRQaaCLS";
	public static final String SSRQaaCLS_FP = "./Data_DDS/SSRQaaCLS.csv";
	public static final String DRQaaUT = "DRQaaUT";
	public static final String DRQaaUT_FP = "./Data_DDS/DRQaaUT.csv";
	public static final String DRQaaBGR = "DRQaaBGR";
	public static final String DRQaaBGR_FP = "./Data_DDS/DRQaaBGR.csv";
	public static final String CLSaaPPL = "CLSaaPPL";
	public static final String CLSaaPPL_FP = "./Data_DDS/CLSaaPPL.csv";
	public static final String CLSaaUTL = "CLSaaUTL";
	public static final String CLSaaUTL_FP = "./Data_DDS/CLSaaUTL.csv";
	public static final String SSRQaaEA = "SSRQaaEA";
	public static final String SSRQaaEA_FP = "./Data_DDS/SSRQaaEA.csv";
	public static final String CLSaaEA = "CLSaaEA";
	public static final String CLSaaEA_FP = "./Data_DDS/CLSaaEA.csv";
	
	
}
